# Site settings
baseurl = "http://majorminorbuild.com/"
languageCode = "en-US"
title = "MajorMinorBuild"
theme = "hugo-theme-cactus-plus"

[params]
    name = "MajorMinorBuild"
    title = "Docker Overview"
    bio = "From introduction to implementation"
    iconFont = "font-awesome"
[social]
  twitter-square = "https://twitter.com/ekiselman"
  github-square = "https://github.com/ekiselman"

